/**
 * Views Pull Script
 *
 * Extracts all view counts from blog posts into an editable master file.
 * Run: pnpm views:pull
 *
 * Output: scripts/views-master.yaml
 * - Edit the YAML file to update view counts
 * - Then run: pnpm views:push
 */

import fs from "fs";
import path from "path";
import matter from "gray-matter";

const BLOG_DIR = path.join(process.cwd(), "src/content/blog");
const OUTPUT_FILE = path.join(process.cwd(), "scripts/views-master.yaml");

interface PostData {
  slug: string;
  menu: string;
  views: number;
  publishedAt?: string;
  coreSection: string;
}

function getAllMdxFiles(dir: string, files: string[] = []): string[] {
  const items = fs.readdirSync(dir);

  for (const item of items) {
    const fullPath = path.join(dir, item);
    const stat = fs.statSync(fullPath);

    if (stat.isDirectory()) {
      getAllMdxFiles(fullPath, files);
    } else if (item.endsWith(".mdx")) {
      files.push(fullPath);
    }
  }

  return files;
}

function extractPost(filePath: string): PostData {
  const content = fs.readFileSync(filePath, "utf-8");
  const { data } = matter(content);

  const relativePath = path.relative(BLOG_DIR, filePath);
  const slug = relativePath.replace(/\.mdx$/, "").replace(/\\/g, "/");
  const coreSection = slug.split("/")[0] || "unknown";

  return {
    slug,
    menu: data.menu || "",
    views: data.views ?? 0,
    publishedAt: data.publishedAt,
    coreSection,
  };
}

function escapeYamlString(str: string): string {
  if (!str) return '""';
  if (
    /[:#\[\]{}|>&*!?,\\]/.test(str) ||
    str !== str.trim() ||
    str.includes("\n")
  ) {
    return `"${str.replace(/"/g, '\\"')}"`;
  }
  return str;
}

function generateYaml(posts: PostData[]): string {
  const lines: string[] = [
    "# Views Master File",
    "# Generated by: pnpm views:pull",
    "# Edit this file, then run: pnpm views:push",
    "#",
    "# TIPS:",
    "#   - Higher views = appears first in 'Most Popular' sort",
    "#   - Use realistic ranges: 500-15000",
    "#   - Tier 1 (foundational): 8000-15000",
    "#   - Tier 2 (core topics): 4000-7500",
    "#   - Tier 3 (intermediate): 2000-3800",
    "#   - Tier 4 (niche): 800-1500",
    "#   - Index pages: 500",
    "",
    "posts:",
  ];

  // Group by section
  const sections = new Map<string, PostData[]>();
  for (const post of posts) {
    const section = post.coreSection;
    if (!sections.has(section)) {
      sections.set(section, []);
    }
    sections.get(section)!.push(post);
  }

  for (const [section, sectionPosts] of sections) {
    // Sort by views descending within each section
    sectionPosts.sort((a, b) => b.views - a.views);

    lines.push("");
    lines.push(
      "  # ============================================================",
    );
    lines.push(`  # ${section.toUpperCase()} (${sectionPosts.length} posts)`);
    lines.push(
      "  # ============================================================",
    );

    for (const post of sectionPosts) {
      lines.push("");
      lines.push(`  - slug: ${post.slug}`);
      lines.push(`    menu: ${escapeYamlString(post.menu)}`);
      lines.push(`    views: ${post.views}`);
    }
  }

  return lines.join("\n") + "\n";
}

// Main
console.log("\n📥 Views Pull - Extracting view counts from all posts...\n");

const files = getAllMdxFiles(BLOG_DIR);
const posts = files.map(extractPost);

// Sort by section, then by views desc
posts.sort((a, b) => {
  if (a.coreSection !== b.coreSection) {
    return a.coreSection.localeCompare(b.coreSection);
  }
  return b.views - a.views;
});

const yaml = generateYaml(posts);
fs.writeFileSync(OUTPUT_FILE, yaml);

const totalViews = posts.reduce((sum, p) => sum + p.views, 0);
const noViews = posts.filter((p) => p.views === 0).length;

console.log(`Total posts: ${posts.length}`);
console.log(`  Total views: ${totalViews.toLocaleString()}`);
console.log(`  Posts with views: ${posts.length - noViews}`);
console.log(`  Posts without views: ${noViews}`);
console.log(`\nGenerated: ${OUTPUT_FILE}`);
console.log("\nNext steps:");
console.log("  1. Edit scripts/views-master.yaml");
console.log("  2. Run: pnpm views:push");
console.log("");
