"""WO-0140 R6a-R pins — legacy tolerance, poisoned markers, bounded-fold remediation.

The two fixture corpora were generated by REAL pre-R6a code (`6955208`, the commit
merged immediately before the R6a branch) — see each JSON's provenance header. They
encode REV-0044 R-1's two triggers: more attributable rejections than the stamped
limit, and a changed budget limit within one cycle. Neither contains a `PRODUCER_*`
event, which is exactly why suites built on fresh databases never see this class.
"""

from __future__ import annotations

import json
import sqlite3
from pathlib import Path

import pytest

from app.events.replay import project_read_models
from app.store.sqlite import SqliteStateStore

pytestmark = pytest.mark.anyio

FIXTURES = Path(__file__).parent / "fixtures"
LEGACY_PRODUCER = "legacy-prod"


def _write_legacy_db(path: str, fixture: str) -> None:
    """Create a fresh schema, then insert the legacy events verbatim."""

    data = json.loads((FIXTURES / f"{fixture}.json").read_text())
    events = data["events"]
    assert events, "fixture must not be empty"
    assert all("producer_" not in e["event_type"] for e in events), (
        "legacy corpora are opener-free by construction"
    )
    conn = sqlite3.connect(path)
    cols = list(events[0].keys())
    conn.executemany(
        f"INSERT INTO execution_events ({', '.join(cols)}) "
        f"VALUES ({', '.join('?' for _ in cols)})",
        [tuple(e[c] for c in cols) for e in events],
    )
    conn.commit()
    conn.close()


async def _fresh_schema(path: str) -> None:
    store = SqliteStateStore(path)
    await store.initialize()


def _read_events(path: str):
    store = SqliteStateStore(path)
    conn = sqlite3.connect(path)
    conn.row_factory = sqlite3.Row
    rows = conn.execute("SELECT * FROM execution_events ORDER BY sequence").fetchall()
    out = [store._execution_event(r) for r in rows]
    conn.close()
    return out


@pytest.mark.parametrize(
    "fixture",
    ["legacy_overbudget_events", "legacy_changed_limit_events"],
)
async def test_legacy_db_opens_and_poisons_exactly_the_offender(
    tmp_path, fixture
) -> None:
    """REV-0044 R-1: a pre-R6a database must OPEN; the offender is quarantined,
    the store is not."""

    path = str(tmp_path / f"{fixture}.db")
    await _fresh_schema(path)
    _write_legacy_db(path, fixture)

    store = SqliteStateStore(path)
    await store.initialize()  # RED today: ProjectionError bricks the whole store

    poisoned = store.poisoned_producers()
    assert set(poisoned) == {LEGACY_PRODUCER}
    marker = poisoned[LEGACY_PRODUCER]
    assert marker.producer_id == LEGACY_PRODUCER
    assert marker.offending_sequence >= 1
    assert marker.last_known_epoch_sequence == 0  # opener-free corpus


@pytest.mark.parametrize(
    "fixture",
    ["legacy_overbudget_events", "legacy_changed_limit_events"],
)
async def test_replay_poisons_the_same_set_as_startup(tmp_path, fixture) -> None:
    """The poisoned marker is DERIVED state: replay must agree with startup."""

    path = str(tmp_path / f"{fixture}.db")
    await _fresh_schema(path)
    _write_legacy_db(path, fixture)

    projection = project_read_models(_read_events(path))
    assert set(projection.poisoned_producers) == {LEGACY_PRODUCER}


async def test_other_producers_unaffected_by_a_poisoned_one(tmp_path) -> None:
    """Tolerance is PER PRODUCER: a healthy producer on the same store works."""

    from datetime import datetime, timedelta, timezone

    path = str(tmp_path / "mixed.db")
    await _fresh_schema(path)
    _write_legacy_db(path, "legacy_overbudget_events")

    store = SqliteStateStore(path)
    await store.initialize()

    now = datetime(2026, 7, 27, 12, 0, 0, tzinfo=timezone.utc)
    result = await store.ingest_signal(
        producer_id="healthy-prod",
        signal_id="sig-ok",
        symbol="AAPL",
        direction="buy",
        issued_at=now,
        ttl_seconds=300,
        suggested_quantity=1,
        suggested_limit_price=None,
        thesis="t",
        provenance={"src": "test"},
        server_max_ttl_seconds=3600,
        cycle_budget_limit=50,
        validation_failed=False,
        raw_fields=None,
        received_at=now + timedelta(seconds=1),
    )
    assert result.outcome == "received"
    assert set(store.poisoned_producers()) == {LEGACY_PRODUCER}


async def test_parity_comparator_sees_poisoned_set_differences(tmp_path) -> None:
    """REV-0039 class guard: the read-model comparator must COMPARE the
    poisoned set, not merely carry it."""

    from app.events.replay import ReadModelProjection, compare_read_models
    from app.events.projectors import PoisonedProducerMarker

    base_kwargs = dict(
        quarantined_symbols=frozenset(),
        timeout_quarantined_order_ids=frozenset(),
    )
    clean = ReadModelProjection(**base_kwargs)
    marked = ReadModelProjection(
        **base_kwargs,
        poisoned_producers={
            LEGACY_PRODUCER: PoisonedProducerMarker(
                producer_id=LEGACY_PRODUCER,
                offending_sequence=51,
                reason="probe",
                last_known_epoch_sequence=0,
            )
        },
    )
    result = compare_read_models("a", clean, "b", marked)
    assert not result.ok
    assert "poisoned_producers" in result.detail


def _ingest_kwargs(producer_id: str, signal_id: str, *, invalid: bool = False, **over):
    from datetime import datetime, timedelta, timezone

    now = datetime(2026, 7, 27, 12, 0, 0, tzinfo=timezone.utc)
    values = dict(
        producer_id=producer_id,
        signal_id=signal_id,
        symbol="AAPL",
        direction="buy",
        issued_at=now,
        ttl_seconds=300,
        suggested_quantity=1,
        suggested_limit_price=None,
        thesis="t",
        provenance={"src": "test"},
        server_max_ttl_seconds=3600,
        cycle_budget_limit=3,
        validation_failed=invalid,
        raw_fields=None,
        received_at=now + timedelta(seconds=1),
    )
    values.update(over)
    return values


async def test_attributable_debit_does_not_rescan_event_log(
    any_store, monkeypatch
) -> None:
    """WO-0140 D-R R-2 scaling pin: the DEBIT path folds nothing.

    Mirrors the delivered rate-path no-rescan pin; the repo's
    test_wo0113_repair_scaling.py gates this class. RED before the
    incremental-debit change: the delivered code re-folds the whole log
    per attributable rejection (REV-0044 R-2, measured 5.5->140.6 ms/reject
    over 100->10k events).
    """

    from app.store.memory import InMemoryStateStore

    await any_store.initialize()
    first = await any_store.ingest_signal(
        **_ingest_kwargs("producer-scale", "seed-signal")
    )
    assert first.outcome == "received"

    def unexpected_fold(*_args, **_kwargs):
        raise AssertionError("attributable debit rescanned the event log")

    if isinstance(any_store, InMemoryStateStore):
        monkeypatch.setattr("app.store.memory.project_producer_rails", unexpected_fold)
        monkeypatch.setattr(
            "app.store.memory.project_producer_rails_tolerant", unexpected_fold
        )
    else:
        monkeypatch.setattr(
            any_store, "_projected_producer_rails_locked", unexpected_fold
        )
        monkeypatch.setattr(
            any_store, "_projected_producer_rails_tolerant_locked", unexpected_fold
        )

    result = await any_store.ingest_signal(
        **_ingest_kwargs("producer-scale", "invalid-1", invalid=True)
    )
    assert result.outcome == "quarantined_validation"
