"""WO-0140 R6a-R pins — legacy tolerance, poisoned markers, bounded-fold remediation.

The two fixture corpora were generated by REAL pre-R6a code (`6955208`, the commit
merged immediately before the R6a branch) — see each JSON's provenance header. They
encode REV-0044 R-1's two triggers: more attributable rejections than the stamped
limit, and a changed budget limit within one cycle. Neither contains a `PRODUCER_*`
event, which is exactly why suites built on fresh databases never see this class.
"""

from __future__ import annotations

import json
import sqlite3
from pathlib import Path

import pytest

from app.events.replay import project_read_models
from app.store.sqlite import SqliteStateStore

pytestmark = pytest.mark.anyio

FIXTURES = Path(__file__).parent / "fixtures"
LEGACY_PRODUCER = "legacy-prod"


def _write_legacy_db(path: str, fixture: str) -> None:
    """Create a fresh schema, then insert the legacy events verbatim."""

    data = json.loads((FIXTURES / f"{fixture}.json").read_text())
    events = data["events"]
    assert events, "fixture must not be empty"
    assert all("producer_" not in e["event_type"] for e in events), (
        "legacy corpora are opener-free by construction"
    )
    conn = sqlite3.connect(path)
    cols = list(events[0].keys())
    conn.executemany(
        f"INSERT INTO execution_events ({', '.join(cols)}) "
        f"VALUES ({', '.join('?' for _ in cols)})",
        [tuple(e[c] for c in cols) for e in events],
    )
    conn.commit()
    conn.close()


async def _fresh_schema(path: str) -> None:
    store = SqliteStateStore(path)
    await store.initialize()


def _read_events(path: str):
    store = SqliteStateStore(path)
    conn = sqlite3.connect(path)
    conn.row_factory = sqlite3.Row
    rows = conn.execute("SELECT * FROM execution_events ORDER BY sequence").fetchall()
    out = [store._execution_event(r) for r in rows]
    conn.close()
    return out


@pytest.mark.parametrize(
    "fixture",
    ["legacy_overbudget_events", "legacy_changed_limit_events"],
)
async def test_legacy_db_opens_and_poisons_exactly_the_offender(
    tmp_path, fixture
) -> None:
    """REV-0044 R-1: a pre-R6a database must OPEN; the offender is quarantined,
    the store is not."""

    path = str(tmp_path / f"{fixture}.db")
    await _fresh_schema(path)
    _write_legacy_db(path, fixture)

    store = SqliteStateStore(path)
    await store.initialize()  # RED today: ProjectionError bricks the whole store

    poisoned = store.poisoned_producers()
    assert set(poisoned) == {LEGACY_PRODUCER}
    marker = poisoned[LEGACY_PRODUCER]
    assert marker.producer_id == LEGACY_PRODUCER
    assert marker.offending_sequence >= 1
    assert marker.last_known_epoch_sequence == 0  # opener-free corpus


@pytest.mark.parametrize(
    "fixture",
    ["legacy_overbudget_events", "legacy_changed_limit_events"],
)
async def test_replay_poisons_the_same_set_as_startup(tmp_path, fixture) -> None:
    """The poisoned marker is DERIVED state: replay must agree with startup."""

    path = str(tmp_path / f"{fixture}.db")
    await _fresh_schema(path)
    _write_legacy_db(path, fixture)

    projection = project_read_models(_read_events(path))
    assert set(projection.poisoned_producers) == {LEGACY_PRODUCER}


async def test_other_producers_unaffected_by_a_poisoned_one(tmp_path) -> None:
    """Tolerance is PER PRODUCER: a healthy producer on the same store works."""

    from datetime import datetime, timedelta, timezone

    path = str(tmp_path / "mixed.db")
    await _fresh_schema(path)
    _write_legacy_db(path, "legacy_overbudget_events")

    store = SqliteStateStore(path)
    await store.initialize()

    now = datetime(2026, 7, 27, 12, 0, 0, tzinfo=timezone.utc)
    result = await store.ingest_signal(
        producer_id="healthy-prod",
        signal_id="sig-ok",
        symbol="AAPL",
        direction="buy",
        issued_at=now,
        ttl_seconds=300,
        suggested_quantity=1,
        suggested_limit_price=None,
        thesis="t",
        provenance={"src": "test"},
        server_max_ttl_seconds=3600,
        cycle_budget_limit=50,
        validation_failed=False,
        raw_fields=None,
        received_at=now + timedelta(seconds=1),
    )
    assert result.outcome == "received"
    assert set(store.poisoned_producers()) == {LEGACY_PRODUCER}


async def test_parity_comparator_sees_poisoned_set_differences(tmp_path) -> None:
    """REV-0039 class guard: the read-model comparator must COMPARE the
    poisoned set, not merely carry it."""

    from app.events.replay import ReadModelProjection, compare_read_models
    from app.events.projectors import PoisonedProducerMarker

    base_kwargs = dict(
        quarantined_symbols=frozenset(),
        timeout_quarantined_order_ids=frozenset(),
    )
    clean = ReadModelProjection(**base_kwargs)
    marked = ReadModelProjection(
        **base_kwargs,
        poisoned_producers={
            LEGACY_PRODUCER: PoisonedProducerMarker(
                producer_id=LEGACY_PRODUCER,
                offending_sequence=51,
                reason="probe",
                last_known_epoch_sequence=0,
            )
        },
    )
    result = compare_read_models("a", clean, "b", marked)
    assert not result.ok
    assert "poisoned_producers" in result.detail


def _ingest_kwargs(producer_id: str, signal_id: str, *, invalid: bool = False, **over):
    from datetime import datetime, timedelta, timezone

    now = datetime(2026, 7, 27, 12, 0, 0, tzinfo=timezone.utc)
    values = dict(
        producer_id=producer_id,
        signal_id=signal_id,
        symbol="AAPL",
        direction="buy",
        issued_at=now,
        ttl_seconds=300,
        suggested_quantity=1,
        suggested_limit_price=None,
        thesis="t",
        provenance={"src": "test"},
        server_max_ttl_seconds=3600,
        cycle_budget_limit=3,
        validation_failed=invalid,
        raw_fields=None,
        received_at=now + timedelta(seconds=1),
    )
    values.update(over)
    return values


async def test_attributable_debit_does_not_rescan_event_log(
    any_store, monkeypatch
) -> None:
    """WO-0140 D-R R-2 scaling pin: the DEBIT path folds nothing.

    Mirrors the delivered rate-path no-rescan pin; the repo's
    test_wo0113_repair_scaling.py gates this class. RED before the
    incremental-debit change: the delivered code re-folds the whole log
    per attributable rejection (REV-0044 R-2, measured 5.5->140.6 ms/reject
    over 100->10k events).
    """

    from app.store.memory import InMemoryStateStore

    await any_store.initialize()
    first = await any_store.ingest_signal(
        **_ingest_kwargs("producer-scale", "seed-signal")
    )
    assert first.outcome == "received"

    def unexpected_fold(*_args, **_kwargs):
        raise AssertionError("attributable debit rescanned the event log")

    if isinstance(any_store, InMemoryStateStore):
        monkeypatch.setattr(
            "app.store.memory.project_producer_rails_tolerant", unexpected_fold
        )
        monkeypatch.setattr("app.store.memory.fold_producer_rail", unexpected_fold)
    else:
        monkeypatch.setattr(
            any_store, "_projected_producer_rails_tolerant_locked", unexpected_fold
        )

    result = await any_store.ingest_signal(
        **_ingest_kwargs("producer-scale", "invalid-1", invalid=True)
    )
    assert result.outcome == "quarantined_validation"


# --------------------------------------------------------------------------- #
# Slice 4 — the three-state release (WO-0140 D-R R-3 + R-4)
# --------------------------------------------------------------------------- #


def _events_from_fixture(fixture: str):
    data = json.loads((FIXTURES / f"{fixture}.json").read_text())
    from app.models import ExecutionEvent

    return [
        ExecutionEvent.model_validate({**e, "payload": json.loads(e["payload"])})
        for e in data["events"]
    ]


async def _sqlite_with_fixture(tmp_path, fixture: str) -> SqliteStateStore:
    path = str(tmp_path / f"{fixture}.db")
    await _fresh_schema(path)
    _write_legacy_db(path, fixture)
    store = SqliteStateStore(path)
    await store.initialize()
    return store


async def test_wedge_producer_is_gated_and_release_heals(tmp_path) -> None:
    """R-4: consumed == limit with no opener (legacy wedge) folds cleanly, is
    boundary-rejected on ingest, and release — state 2 — is the exit."""

    from datetime import datetime, timedelta, timezone

    store = await _sqlite_with_fixture(tmp_path, "legacy_wedge_events")
    assert store.poisoned_producers() == {}  # a wedge is NOT poisoned
    rail = await store.get_producer_rail(LEGACY_PRODUCER)
    assert (rail.cycle_budget_limit, rail.cycle_budget_consumed) == (2, 2)
    assert rail.quarantine_epoch_open is False

    gated = await store.ingest_signal(
        **_ingest_kwargs(LEGACY_PRODUCER, "post-wedge", cycle_budget_limit=2)
    )
    assert gated.outcome == "producer_quarantined"
    assert gated.record is None

    released_at = datetime(2026, 7, 27, 13, 0, 0, tzinfo=timezone.utc)
    healed = await store.release_producer(
        LEGACY_PRODUCER, actor="operator", rejected_count=0, released_at=released_at
    )
    assert healed.cycle_budget_limit is None
    assert healed.cycle_budget_consumed == 0
    assert healed.quarantine_epoch_open is False
    assert healed.quarantine_epoch_sequence == 1  # floor 0 + 1, consumed

    releases = [
        e
        for e in await store.get_execution_events()
        if e.event_type.value == "producer_released"
    ]
    assert len(releases) == 1
    payload = releases[0].payload
    assert payload["epoch_start"] == payload["released_at"]  # zero-width window

    resumed = await store.ingest_signal(
        **_ingest_kwargs(
            LEGACY_PRODUCER,
            "post-heal",
            cycle_budget_limit=2,
            issued_at=released_at,
            received_at=released_at + timedelta(seconds=1),
        )
    )
    assert resumed.outcome == "received"

    projection = project_read_models(await store.get_execution_events())
    assert projection.poisoned_producers == {}
    replay_rail = projection.producer_rails[LEGACY_PRODUCER]
    assert replay_rail.quarantine_epoch_sequence == 1


async def test_poisoned_release_heals_and_stays_healed_across_replay(
    tmp_path,
) -> None:
    """R-1 state 3 + pass-2 F-C: release IS the heal; a healed producer must
    not re-poison on replay, and the fold boundary is the release itself."""

    from datetime import datetime, timedelta, timezone

    store = await _sqlite_with_fixture(tmp_path, "legacy_overbudget_events")
    assert set(store.poisoned_producers()) == {LEGACY_PRODUCER}

    released_at = datetime(2026, 7, 27, 13, 0, 0, tzinfo=timezone.utc)
    healed = await store.release_producer(
        LEGACY_PRODUCER, actor="operator", rejected_count=0, released_at=released_at
    )
    assert store.poisoned_producers() == {}
    assert healed.quarantine_epoch_sequence == 1
    assert healed.cycle_budget_limit is None

    resumed = await store.ingest_signal(
        **_ingest_kwargs(
            LEGACY_PRODUCER,
            "post-heal",
            cycle_budget_limit=50,
            issued_at=released_at,
            received_at=released_at + timedelta(seconds=1),
        )
    )
    assert resumed.outcome == "received"

    projection = project_read_models(await store.get_execution_events())
    assert projection.poisoned_producers == {}  # healed producers STAY healed
    assert projection.producer_rails[LEGACY_PRODUCER].quarantine_epoch_sequence == 1

    fresh = SqliteStateStore(store._db_path)
    await fresh.initialize()
    assert fresh.poisoned_producers() == {}


async def test_state1_release_and_open_epoch_restart_still_work(tmp_path) -> None:
    """The two F-A detonation shapes: a NORMAL open-epoch release, and a
    release after an open-epoch restart. The flat-seed mutant fails both."""

    from datetime import datetime, timezone

    now = datetime(2026, 7, 27, 12, 0, 0, tzinfo=timezone.utc)
    path = str(tmp_path / "state1.db")
    store = SqliteStateStore(path)
    await store.initialize()

    for _ in range(2):  # burst 1: second call breaches, opens epoch 1
        await store.check_and_debit_producer_rate(
            "producer-open", now=now, limit_per_hour=60, burst=1
        )
    rail = await store.get_producer_rail("producer-open")
    assert rail.quarantine_epoch_open is True

    # F-A shape 2: restart with the epoch OPEN, then release on the restarted
    # store — the bounded check must seed row.seq - 1, not row.seq.
    restarted = SqliteStateStore(path)
    await restarted.initialize()
    assert restarted.poisoned_producers() == {}  # a healthy open epoch

    released = await restarted.release_producer(
        "producer-open", actor="operator", rejected_count=3, released_at=now
    )
    assert released.quarantine_epoch_open is False
    assert released.quarantine_epoch_sequence == 1  # preserved, not consumed
    assert "producer-open" not in restarted.poisoned_producers()

    releases = [
        e
        for e in await restarted.get_execution_events()
        if e.event_type.value == "producer_released"
    ]
    assert len(releases) == 1
    payload = releases[0].payload
    assert payload["epoch_start"] != payload["released_at"] or (
        payload["epoch_start"] == payload["released_at"]
        and payload["epoch_start"] == now.isoformat()
    )  # a REAL window: epoch_start is the opener's start


async def test_double_heal_mints_distinct_keys(tmp_path) -> None:
    """Pass-2 F-B: two heals of one producer must key distinctly — the
    carrier never regresses, so heal #2 consumes the NEXT sequence."""

    from datetime import datetime, timezone

    store = await _sqlite_with_fixture(tmp_path, "legacy_overbudget_events")
    released_at = datetime(2026, 7, 27, 13, 0, 0, tzinfo=timezone.utc)
    await store.release_producer(
        LEGACY_PRODUCER, actor="operator", rejected_count=0, released_at=released_at
    )

    # Re-poison via row drift (no matching log anchor at the drifted value).
    assert store._conn is not None
    store._conn.execute(
        "UPDATE signal_producer_rails SET quarantine_epoch_sequence=7 "
        "WHERE producer_id=?",
        (LEGACY_PRODUCER,),
    )
    for _ in range(2):
        await store.check_and_debit_producer_rate(
            LEGACY_PRODUCER, now=released_at, limit_per_hour=60, burst=1
        )
    verdict = await store.check_and_debit_producer_rate(
        LEGACY_PRODUCER, now=released_at, limit_per_hour=60, burst=1
    )
    assert verdict.outcome == "quarantined"
    assert LEGACY_PRODUCER in store.poisoned_producers()

    healed = await store.release_producer(
        LEGACY_PRODUCER, actor="operator", rejected_count=0, released_at=released_at
    )
    assert store.poisoned_producers() == {}
    assert healed.quarantine_epoch_sequence == 2  # floor saw heal #1's key

    keys = [
        e.dedupe_key
        for e in await store.get_execution_events()
        if e.event_type.value == "producer_released"
    ]
    assert len(keys) == 2
    assert len(set(keys)) == 2  # DISTINCT — the F-B collision is dead


async def test_forged_and_interior_zero_width_fail_the_strict_fold() -> None:
    """Pass-2 F-C (narrowed) + F-H: a zero-width release is REFUSED by the
    strict fold when an epoch is open (forged) or mid-cycle (interior)."""

    from datetime import datetime, timezone

    from app.events.projectors import (
        ProjectionError,
        project_producer_rails,
        project_producer_rails_tolerant,
    )
    from app.store.core import (
        producer_quarantined_event,
        producer_released_event,
    )

    now = datetime(2026, 7, 27, 12, 0, 0, tzinfo=timezone.utc)
    later = datetime(2026, 7, 27, 12, 5, 0, tzinfo=timezone.utc)

    def _seq(events):
        out = []
        for i, e in enumerate(events, start=1):
            out.append(e.model_copy(update={"sequence": i}))
        return out

    # Forged: epoch OPEN (started at `now`), zero-width release at `later`.
    opener = producer_quarantined_event(
        producer_id="p-forged",
        breach_trigger="rate_breach",
        epoch_start=now,
        epoch_sequence=1,
        bucket_capacity=5,
    )
    forged_release = producer_released_event(
        producer_id="p-forged",
        actor="mallory",
        rejected_count=0,
        epoch_start=later,
        released_at=later,
        epoch_sequence=2,
    )
    forged_log = _seq([opener, forged_release])
    with pytest.raises(ProjectionError):
        project_producer_rails(forged_log)
    _, poisoned = project_producer_rails_tolerant(forged_log)
    assert "p-forged" in poisoned  # the funnel, not a silent fold

    # Interior: one real attributable rejection (consumed 1 of limit 5, from
    # the fixture corpus), then a zero-width release — laundering a partially
    # consumed budget must be refused (F-H).
    first_attributable = _events_from_fixture("legacy_changed_limit_events")[0]
    interior_release = producer_released_event(
        producer_id=LEGACY_PRODUCER,
        actor="mallory",
        rejected_count=0,
        epoch_start=later,
        released_at=later,
        epoch_sequence=1,
    )
    interior_log = _seq([first_attributable, interior_release])
    with pytest.raises(ProjectionError):
        project_producer_rails(interior_log)
    _, poisoned = project_producer_rails_tolerant(interior_log)
    assert LEGACY_PRODUCER in poisoned


# --------------------------------------------------------------------------- #
# Slice 5 — read-structural, write-capped (WO-0140 D-R R-5)
# --------------------------------------------------------------------------- #


async def test_logged_values_above_current_caps_still_fold() -> None:
    """R-5: an append-only log is never re-judged by a mutable constant.

    Values above today's ratified caps, once LOGGED, must fold — lowering a
    cap must never retroactively brick startup or replay. Caps bind at WRITE
    time only (the builder pins below this one).
    """

    from datetime import datetime, timezone

    from app.events.projectors import project_producer_rails
    from app.store.core import producer_quarantined_event, producer_released_event

    now = datetime(2026, 7, 27, 12, 0, 0, tzinfo=timezone.utc)

    def _seq(events):
        return [e.model_copy(update={"sequence": i}) for i, e in enumerate(events, 1)]

    opener = producer_quarantined_event(
        producer_id="p-cap",
        breach_trigger="rate_breach",
        epoch_start=now,
        epoch_sequence=1,
        bucket_capacity=100,
    )
    opener = opener.model_copy(
        update={"payload": {**opener.payload, "bucket_capacity": 101}}
    )
    release = producer_released_event(
        producer_id="p-cap",
        actor="operator",
        rejected_count=0,
        epoch_start=now,
        released_at=now,
        epoch_sequence=1,
    )
    release = release.model_copy(
        update={"payload": {**release.payload, "rejected_count": 10_001}}
    )
    rail = project_producer_rails(_seq([opener, release]))["p-cap"]
    assert rail.quarantine_epoch_open is False  # both folded, no ProjectionError

    over_limit = _events_from_fixture("legacy_changed_limit_events")[0]
    over_limit = over_limit.model_copy(
        update={
            "payload": {**over_limit.payload, "cycle_budget_limit": 1001},
            "sequence": 1,
        }
    )
    rail = project_producer_rails([over_limit])[LEGACY_PRODUCER]
    assert rail.cycle_budget_limit == 1001  # logged truth, folded as-is


async def test_row_with_tokens_above_burst_cap_still_serves_after_reopen(
    tmp_path,
) -> None:
    """R-5 below the fold: class-B durable state no rebuild can heal must not
    be re-judged by a mutable cap at the row validator either."""

    path = str(tmp_path / "capdrift.db")
    store = SqliteStateStore(path)
    await store.initialize()
    r = await store.ingest_signal(**_ingest_kwargs("p-cap", "s-1"))
    assert r.outcome == "received"

    assert store._conn is not None
    store._conn.execute(
        "UPDATE signal_producer_rails SET rate_tokens=150.0, "
        "rate_refill_anchor='2026-07-27T12:00:00+00:00' WHERE producer_id='p-cap'"
    )
    store._conn.commit()

    reopened = SqliteStateStore(path)
    await reopened.initialize()  # a lowered cap must never brick the store
    rail = await reopened.get_producer_rail("p-cap")
    assert rail.rate_tokens == 150.0  # served, not refused


async def test_ratified_cap_literals_are_single_sourced() -> None:
    """R-7 closure: every ratified cap literal lives in app/models.py ONLY."""

    import re

    app_dir = Path(__file__).resolve().parents[1] / "app"
    offenders: list[str] = []
    for py in app_dir.rglob("*.py"):
        rel = str(py.relative_to(app_dir.parent))
        text = py.read_text()
        for name in (
            "SIGNAL_INVALID_BUDGET_HARD_CAP",
            "SIGNAL_RATE_LIMIT_PER_HOUR_MAX",
            "SIGNAL_RATE_BURST_MAX",
            "SIGNAL_REJECTED_COUNT_MAX",
        ):
            if re.search(rf"^{name}\s*=\s*\d", text, re.M) and rel != "app/models.py":
                offenders.append(f"{rel}: {name}")
        if rel != "app/models.py" and re.search(r"<=\s*1000\b", text):
            offenders.append(f"{rel}: bare 1000 bound")
    assert (app_dir / "models.py").exists()
    assert offenders == [], offenders


async def test_poisoned_producer_gets_403_through_the_mounted_app() -> None:
    """Refutation finding 5 (the D-R6a-8 class): the store-gate poisoned
    rejection composes through facade coercion and the route's outcome map —
    provable only at runtime; every static gate is blind to it."""

    from fastapi.testclient import TestClient

    from app.events.projectors import PoisonedProducerMarker
    from app.store.memory import InMemoryStateStore
    from tests.signal_seat_helpers import (
        _IN_PROCESS_TEST_AUTHORITY,
        PRODUCER_KEY,
        build_flag_on_app,
        flag_on_settings,
    )

    headers = {"X-Producer-Key": PRODUCER_KEY}

    store = InMemoryStateStore()
    app = build_flag_on_app(
        test_authority=_IN_PROCESS_TEST_AUTHORITY,
        store=store,
        settings=flag_on_settings(),
    )
    with TestClient(app, raise_server_exceptions=False) as client:
        store._poisoned_producers["vibe-trading"] = PoisonedProducerMarker(
            producer_id="vibe-trading",
            offending_sequence=1,
            reason="probe",
            last_known_epoch_sequence=0,
        )
        before = client.portal.call(store.get_execution_events)
        response = client.post(
            "/api/signals",
            json={
                "signal_id": "poisoned-sig",
                "symbol": "AAPL",
                "direction": "buy",
                "thesis": "test",
                "provenance": {"model": "test"},
            },
            headers=headers,
        )
        assert response.status_code == 403
        assert response.json()["reason"] == "producer_quarantined"
        assert client.portal.call(store.get_execution_events) == before


async def test_open_epoch_drift_poisons_instead_of_raising(tmp_path) -> None:
    """Refutation finding 1 (P0): drift that detonates INSIDE a strict applier
    (ProjectionError, not InvalidEventError) must poison per producer at every
    boundary — never escape as an uncaught exception, never wedge release."""

    from datetime import datetime, timezone

    now = datetime(2026, 7, 27, 12, 0, 0, tzinfo=timezone.utc)
    path = str(tmp_path / "opendrift.db")
    store = SqliteStateStore(path)
    await store.initialize()
    for _ in range(2):  # burst 1: opens epoch 1
        await store.check_and_debit_producer_rate(
            "p-drift", now=now, limit_per_hour=60, burst=1
        )

    # Drift the carrier while the epoch is OPEN: the bounded fold's segment
    # contains the opener, so the strict applier's current+1 check detonates.
    assert store._conn is not None
    store._conn.execute(
        "UPDATE signal_producer_rails SET quarantine_epoch_sequence=4 "
        "WHERE producer_id='p-drift'"
    )
    store._conn.commit()

    released = await store.release_producer(
        "p-drift", actor="operator", rejected_count=0, released_at=now
    )
    # The drift funnelled into the heal — no uncaught ProjectionError, no wedge.
    assert released.quarantine_epoch_open is False
    assert store.poisoned_producers() == {}  # healed in the same call
