"""WO-0140 R6a-R pins — legacy tolerance, invalid-projection markers, bounded-fold remediation.

The two fixture corpora were generated by REAL pre-R6a code (`6955208`, the commit
merged immediately before the R6a branch) — see each JSON's provenance header. They
encode REV-0044 R-1's two triggers: more attributable rejections than the stamped
limit, and a changed budget limit within one cycle. Neither contains a `PRODUCER_*`
event, which is exactly why suites built on fresh databases never see this class.
"""

from __future__ import annotations

import json
import sqlite3
from pathlib import Path

import pytest

from app.events.replay import project_read_models
from app.store.sqlite import SqliteStateStore

pytestmark = pytest.mark.anyio

FIXTURES = Path(__file__).parent / "fixtures"
LEGACY_PRODUCER = "legacy-prod"


def _write_legacy_db(path: str, fixture: str) -> None:
    """Create a fresh schema, then insert the legacy events verbatim."""

    data = json.loads((FIXTURES / f"{fixture}.json").read_text())
    events = data["events"]
    assert events, "fixture must not be empty"
    assert all("producer_" not in e["event_type"] for e in events), (
        "legacy corpora are opener-free by construction"
    )
    conn = sqlite3.connect(path)
    cols = list(events[0].keys())
    conn.executemany(
        f"INSERT INTO execution_events ({', '.join(cols)}) "
        f"VALUES ({', '.join('?' for _ in cols)})",
        [tuple(e[c] for c in cols) for e in events],
    )
    conn.commit()
    conn.close()


async def _fresh_schema(path: str) -> None:
    store = SqliteStateStore(path)
    await store.initialize()


def _read_events(path: str):
    store = SqliteStateStore(path)
    conn = sqlite3.connect(path)
    conn.row_factory = sqlite3.Row
    rows = conn.execute("SELECT * FROM execution_events ORDER BY sequence").fetchall()
    out = [store._execution_event(r) for r in rows]
    conn.close()
    return out


@pytest.mark.parametrize(
    "fixture",
    ["legacy_overbudget_events", "legacy_changed_limit_events"],
)
async def test_legacy_db_opens_and_invalidates_exactly_the_offender(
    tmp_path, fixture
) -> None:
    """REV-0044 R-1: a pre-R6a database must OPEN; the offender is quarantined,
    the store is not."""

    path = str(tmp_path / f"{fixture}.db")
    await _fresh_schema(path)
    _write_legacy_db(path, fixture)

    store = SqliteStateStore(path)
    await store.initialize()  # RED today: ProjectionError bricks the whole store

    invalidated = store.invalid_projection_markers()
    assert set(invalidated) == {LEGACY_PRODUCER}
    marker = invalidated[LEGACY_PRODUCER]
    assert marker.producer_id == LEGACY_PRODUCER
    assert marker.offending_sequence >= 1
    assert marker.last_known_epoch_sequence == 0  # opener-free corpus


@pytest.mark.parametrize(
    "fixture",
    ["legacy_overbudget_events", "legacy_changed_limit_events"],
)
async def test_replay_invalidates_the_same_set_as_startup(tmp_path, fixture) -> None:
    """The invalid-projection marker is DERIVED state: replay must agree with startup."""

    path = str(tmp_path / f"{fixture}.db")
    await _fresh_schema(path)
    _write_legacy_db(path, fixture)

    projection = project_read_models(_read_events(path))
    assert set(projection.invalid_projection_markers) == {LEGACY_PRODUCER}


async def test_other_producers_unaffected_by_a_invalidated_one(tmp_path) -> None:
    """Tolerance is PER PRODUCER: a healthy producer on the same store works."""

    from datetime import datetime, timedelta, timezone

    path = str(tmp_path / "mixed.db")
    await _fresh_schema(path)
    _write_legacy_db(path, "legacy_overbudget_events")

    store = SqliteStateStore(path)
    await store.initialize()

    now = datetime(2026, 7, 27, 12, 0, 0, tzinfo=timezone.utc)
    result = await store.ingest_signal(
        producer_id="healthy-prod",
        signal_id="sig-ok",
        symbol="AAPL",
        direction="buy",
        issued_at=now,
        ttl_seconds=300,
        suggested_quantity=1,
        suggested_limit_price=None,
        thesis="t",
        provenance={"src": "test"},
        server_max_ttl_seconds=3600,
        cycle_budget_limit=50,
        validation_failed=False,
        raw_fields=None,
        received_at=now + timedelta(seconds=1),
    )
    assert result.outcome == "received"
    assert set(store.invalid_projection_markers()) == {LEGACY_PRODUCER}


async def test_parity_comparator_sees_invalidated_set_differences(tmp_path) -> None:
    """REV-0039 class guard: the read-model comparator must COMPARE the
    invalid-projection set, not merely carry it."""

    from app.events.replay import ReadModelProjection, compare_read_models
    from app.events.projectors import InvalidProjectionMarker

    base_kwargs = dict(
        quarantined_symbols=frozenset(),
        timeout_quarantined_order_ids=frozenset(),
    )
    clean = ReadModelProjection(**base_kwargs)
    marked = ReadModelProjection(
        **base_kwargs,
        invalid_projection_markers={
            LEGACY_PRODUCER: InvalidProjectionMarker(
                producer_id=LEGACY_PRODUCER,
                offending_sequence=51,
                reason="probe",
                last_known_epoch_sequence=0,
            )
        },
    )
    result = compare_read_models("a", clean, "b", marked)
    assert not result.ok
    assert "invalid_projection_markers" in result.detail


def _ingest_kwargs(producer_id: str, signal_id: str, *, invalid: bool = False, **over):
    from datetime import datetime, timedelta, timezone

    now = datetime(2026, 7, 27, 12, 0, 0, tzinfo=timezone.utc)
    values = dict(
        producer_id=producer_id,
        signal_id=signal_id,
        symbol="AAPL",
        direction="buy",
        issued_at=now,
        ttl_seconds=300,
        suggested_quantity=1,
        suggested_limit_price=None,
        thesis="t",
        provenance={"src": "test"},
        server_max_ttl_seconds=3600,
        cycle_budget_limit=3,
        validation_failed=invalid,
        raw_fields=None,
        received_at=now + timedelta(seconds=1),
    )
    values.update(over)
    return values


async def test_attributable_debit_does_not_rescan_event_log(
    any_store, monkeypatch
) -> None:
    """WO-0140 D-R R-2 scaling pin: the DEBIT path folds nothing.

    Mirrors the delivered rate-path no-rescan pin; the repo's
    test_wo0113_repair_scaling.py gates this class. RED before the
    incremental-debit change: the delivered code re-folds the whole log
    per attributable rejection (REV-0044 R-2, measured 5.5->140.6 ms/reject
    over 100->10k events).
    """

    from app.store.memory import InMemoryStateStore

    await any_store.initialize()
    first = await any_store.ingest_signal(
        **_ingest_kwargs("producer-scale", "seed-signal")
    )
    assert first.outcome == "received"

    def unexpected_fold(*_args, **_kwargs):
        raise AssertionError("attributable debit rescanned the event log")

    if isinstance(any_store, InMemoryStateStore):
        monkeypatch.setattr(
            "app.store.memory.project_producer_rails_tolerant", unexpected_fold
        )
        monkeypatch.setattr("app.store.memory.fold_producer_rail", unexpected_fold)
    else:
        monkeypatch.setattr(
            any_store, "_projected_producer_rails_tolerant_locked", unexpected_fold
        )

    result = await any_store.ingest_signal(
        **_ingest_kwargs("producer-scale", "invalid-1", invalid=True)
    )
    assert result.outcome == "quarantined_validation"


# --------------------------------------------------------------------------- #
# Slice 4 — the three-state release (WO-0140 D-R R-3 + R-4)
# --------------------------------------------------------------------------- #


def _events_from_fixture(fixture: str):
    data = json.loads((FIXTURES / f"{fixture}.json").read_text())
    from app.models import ExecutionEvent

    return [
        ExecutionEvent.model_validate({**e, "payload": json.loads(e["payload"])})
        for e in data["events"]
    ]


async def _sqlite_with_fixture(tmp_path, fixture: str) -> SqliteStateStore:
    path = str(tmp_path / f"{fixture}.db")
    await _fresh_schema(path)
    _write_legacy_db(path, fixture)
    store = SqliteStateStore(path)
    await store.initialize()
    return store


async def test_wedge_producer_is_gated_and_release_heals(tmp_path) -> None:
    """R-4: consumed == limit with no opener (legacy wedge) folds cleanly, is
    boundary-rejected on ingest, and release — state 2 — is the exit."""

    from datetime import datetime, timedelta, timezone

    store = await _sqlite_with_fixture(tmp_path, "legacy_wedge_events")
    assert store.invalid_projection_markers() == {}  # a wedge is NOT invalidated
    rail = await store.get_producer_rail(LEGACY_PRODUCER)
    assert (rail.cycle_budget_limit, rail.cycle_budget_consumed) == (2, 2)
    assert rail.quarantine_epoch_open is False

    gated = await store.ingest_signal(
        **_ingest_kwargs(LEGACY_PRODUCER, "post-wedge", cycle_budget_limit=2)
    )
    assert gated.outcome == "producer_quarantined"
    assert gated.record is None

    released_at = datetime(2026, 7, 27, 13, 0, 0, tzinfo=timezone.utc)
    healed = await store.release_producer(
        LEGACY_PRODUCER, actor="operator", rejected_count=0, released_at=released_at
    )
    assert healed.cycle_budget_limit is None
    assert healed.cycle_budget_consumed == 0
    assert healed.quarantine_epoch_open is False
    assert healed.quarantine_epoch_sequence == 1  # floor 0 + 1, consumed

    releases = [
        e
        for e in await store.get_execution_events()
        if e.event_type.value == "producer_released"
    ]
    assert len(releases) == 1
    payload = releases[0].payload
    assert payload["epoch_start"] == payload["released_at"]  # zero-width window

    resumed = await store.ingest_signal(
        **_ingest_kwargs(
            LEGACY_PRODUCER,
            "post-heal",
            cycle_budget_limit=2,
            issued_at=released_at,
            received_at=released_at + timedelta(seconds=1),
        )
    )
    assert resumed.outcome == "received"

    projection = project_read_models(await store.get_execution_events())
    assert projection.invalid_projection_markers == {}
    replay_rail = projection.producer_rails[LEGACY_PRODUCER]
    assert replay_rail.quarantine_epoch_sequence == 1


async def test_invalidated_release_heals_and_stays_healed_across_replay(
    tmp_path,
) -> None:
    """R-1 state 3 + pass-2 F-C: release IS the heal; a healed producer must
    not re-invalidate on replay, and the fold boundary is the release itself."""

    from datetime import datetime, timedelta, timezone

    store = await _sqlite_with_fixture(tmp_path, "legacy_overbudget_events")
    assert set(store.invalid_projection_markers()) == {LEGACY_PRODUCER}

    released_at = datetime(2026, 7, 27, 13, 0, 0, tzinfo=timezone.utc)
    healed = await store.release_producer(
        LEGACY_PRODUCER, actor="operator", rejected_count=0, released_at=released_at
    )
    assert store.invalid_projection_markers() == {}
    assert healed.quarantine_epoch_sequence == 1
    assert healed.cycle_budget_limit is None

    resumed = await store.ingest_signal(
        **_ingest_kwargs(
            LEGACY_PRODUCER,
            "post-heal",
            cycle_budget_limit=50,
            issued_at=released_at,
            received_at=released_at + timedelta(seconds=1),
        )
    )
    assert resumed.outcome == "received"

    projection = project_read_models(await store.get_execution_events())
    assert projection.invalid_projection_markers == {}  # healed producers STAY healed
    assert projection.producer_rails[LEGACY_PRODUCER].quarantine_epoch_sequence == 1

    fresh = SqliteStateStore(store._db_path)
    await fresh.initialize()
    assert fresh.invalid_projection_markers() == {}


async def test_state1_release_and_open_epoch_restart_still_work(
    tmp_path, monkeypatch
) -> None:
    """The two F-A detonation shapes: a NORMAL open-epoch release, and a
    release after an open-epoch restart. The flat-seed mutant fails both.

    REV-0045 P0-2: the final released state alone does not discriminate the
    mutant, because Option A's log-classification fallback silently produces
    the identical correct numbers whenever the bounded check wrongly raises
    on a HEALTHY segment. The behavioral property that actually pins the
    formula: a healthy open epoch must clear the bounded check on the first
    try and must never transit ``invalid_projection_markers`` at all. A spy on the
    bounded-check method (not just the final outcome) is what turns red when
    the ``- (1 if ... else 0)`` term is removed.
    """

    from datetime import datetime, timezone

    from app.events.projectors import ProjectionError
    from app.store.base import InvalidEventError

    now = datetime(2026, 7, 27, 12, 0, 0, tzinfo=timezone.utc)
    path = str(tmp_path / "state1.db")
    store = SqliteStateStore(path)
    await store.initialize()

    for _ in range(2):  # burst 1: second call breaches, opens epoch 1
        await store.check_and_debit_producer_rate(
            "producer-open", now=now, limit_per_hour=60, burst=1
        )
    rail = await store.get_producer_rail("producer-open")
    assert rail.quarantine_epoch_open is True

    # F-A shape 2: restart with the epoch OPEN, then release on the restarted
    # store — the bounded check must seed row.seq - 1, not row.seq.
    restarted = SqliteStateStore(path)
    await restarted.initialize()
    assert restarted.invalid_projection_markers() == {}  # a healthy open epoch

    bounded_check_raised: list[BaseException] = []
    original_bounded_check = SqliteStateStore._authoritative_epoch_sequence_locked

    def _spy(self, cur, producer_id, cached):
        try:
            return original_bounded_check(self, cur, producer_id, cached)
        except (InvalidEventError, ProjectionError) as exc:
            bounded_check_raised.append(exc)
            raise

    monkeypatch.setattr(SqliteStateStore, "_authoritative_epoch_sequence_locked", _spy)

    released = await restarted.release_producer(
        "producer-open", actor="operator", rejected_count=3, released_at=now
    )
    # The bounded check must succeed on the FIRST try — a healthy open epoch
    # must never be routed through the invalidate-then-heal fallback, which
    # would mask a broken seed formula by re-deriving the same numbers from
    # a full, unseeded refold.
    assert bounded_check_raised == []
    assert released.quarantine_epoch_open is False
    assert released.quarantine_epoch_sequence == 1  # preserved, not consumed
    assert "producer-open" not in restarted.invalid_projection_markers()

    releases = [
        e
        for e in await restarted.get_execution_events()
        if e.event_type.value == "producer_released"
    ]
    assert len(releases) == 1
    payload = releases[0].payload
    assert payload["epoch_start"] != payload["released_at"] or (
        payload["epoch_start"] == payload["released_at"]
        and payload["epoch_start"] == now.isoformat()
    )  # a REAL window: epoch_start is the opener's start


async def test_double_heal_mints_distinct_keys(tmp_path) -> None:
    """Pass-2 F-B: two heals of one producer must key distinctly — the
    carrier never regresses, so heal #2 consumes the NEXT sequence."""

    from datetime import datetime, timezone

    store = await _sqlite_with_fixture(tmp_path, "legacy_overbudget_events")
    released_at = datetime(2026, 7, 27, 13, 0, 0, tzinfo=timezone.utc)
    await store.release_producer(
        LEGACY_PRODUCER, actor="operator", rejected_count=0, released_at=released_at
    )

    # Re-invalidation via row drift (no matching log anchor at the drifted value).
    assert store._conn is not None
    store._conn.execute(
        "UPDATE signal_producer_rails SET quarantine_epoch_sequence=7 "
        "WHERE producer_id=?",
        (LEGACY_PRODUCER,),
    )
    for _ in range(2):
        await store.check_and_debit_producer_rate(
            LEGACY_PRODUCER, now=released_at, limit_per_hour=60, burst=1
        )
    verdict = await store.check_and_debit_producer_rate(
        LEGACY_PRODUCER, now=released_at, limit_per_hour=60, burst=1
    )
    assert verdict.outcome == "quarantined"
    assert LEGACY_PRODUCER in store.invalid_projection_markers()

    healed = await store.release_producer(
        LEGACY_PRODUCER, actor="operator", rejected_count=0, released_at=released_at
    )
    assert store.invalid_projection_markers() == {}
    assert healed.quarantine_epoch_sequence == 2  # floor saw heal #1's key

    keys = [
        e.dedupe_key
        for e in await store.get_execution_events()
        if e.event_type.value == "producer_released"
    ]
    assert len(keys) == 2
    assert len(set(keys)) == 2  # DISTINCT — the F-B collision is dead


async def test_invalid_fixture_and_interior_zero_width_fail_the_strict_fold() -> None:
    """Pass-2 F-C (narrowed) + F-H: a zero-width release is REFUSED by the
    strict fold when an epoch is open (deliberately invalid fixture) or mid-cycle (interior)."""

    from datetime import datetime, timezone

    from app.events.projectors import (
        ProjectionError,
        project_producer_rails,
        project_producer_rails_tolerant,
    )
    from app.store.core import (
        producer_quarantined_event,
        producer_released_event,
    )

    now = datetime(2026, 7, 27, 12, 0, 0, tzinfo=timezone.utc)
    later = datetime(2026, 7, 27, 12, 5, 0, tzinfo=timezone.utc)

    def _seq(events):
        out = []
        for i, e in enumerate(events, start=1):
            out.append(e.model_copy(update={"sequence": i}))
        return out

    # Invalid fixture: epoch OPEN (started at `now`), zero-width release at `later`.
    opener = producer_quarantined_event(
        producer_id="p-invalid-fixture",
        breach_trigger="rate_breach",
        epoch_start=now,
        epoch_sequence=1,
        bucket_capacity=5,
    )
    invalid_fixture_release = producer_released_event(
        producer_id="p-invalid-fixture",
        actor="operator",
        rejected_count=0,
        epoch_start=later,
        released_at=later,
        epoch_sequence=2,
    )
    invalid_fixture_log = _seq([opener, invalid_fixture_release])
    with pytest.raises(ProjectionError):
        project_producer_rails(invalid_fixture_log)
    _, invalidated = project_producer_rails_tolerant(invalid_fixture_log)
    assert "p-invalid-fixture" in invalidated  # the funnel, not a silent fold

    # Interior: one real attributable rejection (consumed 1 of limit 5, from
    # the fixture corpus), then a zero-width release — an unratified cycle
    # reset of a partially consumed budget must be refused (F-H).
    first_attributable = _events_from_fixture("legacy_changed_limit_events")[0]
    interior_release = producer_released_event(
        producer_id=LEGACY_PRODUCER,
        actor="operator",
        rejected_count=0,
        epoch_start=later,
        released_at=later,
        epoch_sequence=1,
    )
    interior_log = _seq([first_attributable, interior_release])
    with pytest.raises(ProjectionError):
        project_producer_rails(interior_log)
    _, invalidated = project_producer_rails_tolerant(interior_log)
    assert LEGACY_PRODUCER in invalidated


async def test_zero_width_heal_requires_the_exact_next_sequence_not_any_higher() -> (
    None
):
    """REV-0045 expanded P1-1: a zero-width release from a KNOWN (already
    folded, not invalidated) zero state must consume EXACTLY the next sequence
    — skipping ahead to a higher one is refused, not only a regression at or
    below the carrier."""

    from datetime import datetime, timezone

    from app.events.projectors import ProjectionError, project_producer_rails
    from app.store.core import producer_released_event

    now = datetime(2026, 7, 27, 12, 0, 0, tzinfo=timezone.utc)

    skipping_release = producer_released_event(
        producer_id="p-skip",
        actor="operator",
        rejected_count=0,
        epoch_start=now,
        released_at=now,
        epoch_sequence=5,  # the zero state's carrier is 0; next is 1, not 5
    ).model_copy(update={"sequence": 1})
    with pytest.raises(ProjectionError, match="expected the exact next"):
        project_producer_rails([skipping_release])


async def test_invalidated_heal_requires_full_structural_validation() -> None:
    """REV-0045 P0-4: the invalid-marker heal fast path is not a lesser standard.
    A malformed recovery event (invalid actor) or a non-exact-next sequence
    must NOT clear the invalid-projection marker just because it is zero-width — every
    release, including a heal, passes through the SAME strict validator."""

    from datetime import datetime, timezone

    from app.events.projectors import project_producer_rails_tolerant
    from app.store.core import producer_released_event

    later = datetime(2026, 7, 27, 13, 0, 0, tzinfo=timezone.utc)
    fixture_events = _events_from_fixture("legacy_overbudget_events")
    next_sequence = max(e.sequence for e in fixture_events) + 1

    _, invalidated = project_producer_rails_tolerant(fixture_events)
    assert LEGACY_PRODUCER in invalidated  # baseline: the fixture alone invalidates it

    good_release = producer_released_event(
        producer_id=LEGACY_PRODUCER,
        actor="operator",
        rejected_count=0,
        epoch_start=later,
        released_at=later,
        epoch_sequence=1,
    ).model_copy(update={"sequence": next_sequence})
    _, invalidated = project_producer_rails_tolerant([*fixture_events, good_release])
    assert LEGACY_PRODUCER not in invalidated  # baseline sanity: this DOES heal

    bad_actor_release = good_release.model_copy(
        update={"payload": {**good_release.payload, "actor": " operator "}}
    )
    _, invalidated = project_producer_rails_tolerant(
        [*fixture_events, bad_actor_release]
    )
    assert LEGACY_PRODUCER in invalidated  # malformed actor must NOT heal it

    wrong_sequence_release = producer_released_event(
        producer_id=LEGACY_PRODUCER,
        actor="operator",
        rejected_count=0,
        epoch_start=later,
        released_at=later,
        epoch_sequence=2,  # skips ahead — prior high-water is 0, next is 1
    ).model_copy(update={"sequence": next_sequence})
    _, invalidated = project_producer_rails_tolerant(
        [*fixture_events, wrong_sequence_release]
    )
    assert LEGACY_PRODUCER in invalidated  # skipped sequence must NOT heal it


# --------------------------------------------------------------------------- #
# Slice 5 — read-structural, write-capped (WO-0140 D-R R-5)
# --------------------------------------------------------------------------- #


async def test_logged_values_above_current_caps_still_fold() -> None:
    """R-5: an append-only log is never re-judged by a mutable constant.

    Values above today's ratified caps, once LOGGED, must fold — lowering a
    cap must never retroactively brick startup or replay. Caps bind at WRITE
    time only (the builder pins below this one).
    """

    from datetime import datetime, timezone

    from app.events.projectors import project_producer_rails
    from app.store.core import producer_quarantined_event, producer_released_event

    now = datetime(2026, 7, 27, 12, 0, 0, tzinfo=timezone.utc)

    def _seq(events):
        return [e.model_copy(update={"sequence": i}) for i, e in enumerate(events, 1)]

    opener = producer_quarantined_event(
        producer_id="p-cap",
        breach_trigger="rate_breach",
        epoch_start=now,
        epoch_sequence=1,
        bucket_capacity=100,
    )
    opener = opener.model_copy(
        update={"payload": {**opener.payload, "bucket_capacity": 101}}
    )
    release = producer_released_event(
        producer_id="p-cap",
        actor="operator",
        rejected_count=0,
        epoch_start=now,
        released_at=now,
        epoch_sequence=1,
    )
    release = release.model_copy(
        update={"payload": {**release.payload, "rejected_count": 10_001}}
    )
    rail = project_producer_rails(_seq([opener, release]))["p-cap"]
    assert rail.quarantine_epoch_open is False  # both folded, no ProjectionError

    over_limit = _events_from_fixture("legacy_changed_limit_events")[0]
    over_limit = over_limit.model_copy(
        update={
            "payload": {**over_limit.payload, "cycle_budget_limit": 1001},
            "sequence": 1,
        }
    )
    rail = project_producer_rails([over_limit])[LEGACY_PRODUCER]
    assert rail.cycle_budget_limit == 1001  # logged truth, folded as-is


async def test_row_with_tokens_above_burst_cap_still_serves_after_reopen(
    tmp_path,
) -> None:
    """R-5 below the fold: class-B durable state no rebuild can heal must not
    be re-judged by a mutable cap at the row validator either."""

    path = str(tmp_path / "capdrift.db")
    store = SqliteStateStore(path)
    await store.initialize()
    r = await store.ingest_signal(**_ingest_kwargs("p-cap", "s-1"))
    assert r.outcome == "received"

    assert store._conn is not None
    store._conn.execute(
        "UPDATE signal_producer_rails SET rate_tokens=150.0, "
        "rate_refill_anchor='2026-07-27T12:00:00+00:00' WHERE producer_id='p-cap'"
    )
    store._conn.commit()

    reopened = SqliteStateStore(path)
    await reopened.initialize()  # a lowered cap must never brick the store
    rail = await reopened.get_producer_rail("p-cap")
    assert rail.rate_tokens == 150.0  # served, not refused


async def test_ratified_cap_literals_are_single_sourced() -> None:
    """R-7 closure: every ratified cap literal lives in app/models.py ONLY."""

    import re

    app_dir = Path(__file__).resolve().parents[1] / "app"
    offenders: list[str] = []
    for py in app_dir.rglob("*.py"):
        rel = py.relative_to(app_dir.parent).as_posix()
        text = py.read_text()
        for name in (
            "SIGNAL_INVALID_BUDGET_HARD_CAP",
            "SIGNAL_RATE_LIMIT_PER_HOUR_MAX",
            "SIGNAL_RATE_BURST_MAX",
            "SIGNAL_REJECTED_COUNT_MAX",
        ):
            if re.search(rf"^{name}\s*=\s*\d", text, re.M) and rel != "app/models.py":
                offenders.append(f"{rel}: {name}")
        if rel != "app/models.py" and re.search(r"<=\s*1000\b", text):
            offenders.append(f"{rel}: bare 1000 bound")
    assert (app_dir / "models.py").exists()
    assert offenders == [], offenders


async def test_invalidated_producer_gets_403_through_the_mounted_app() -> None:
    """Refutation finding 5 (the D-R6a-8 class): the store-gate invalidated
    rejection composes through facade coercion and the route's outcome map —
    provable only at runtime; every static gate is blind to it."""

    from fastapi.testclient import TestClient

    from app.events.projectors import InvalidProjectionMarker
    from app.store.memory import InMemoryStateStore
    from tests.signal_seat_helpers import (
        _IN_PROCESS_TEST_AUTHORITY,
        PRODUCER_KEY,
        build_flag_on_app,
        flag_on_settings,
    )

    headers = {"X-Producer-Key": PRODUCER_KEY}

    store = InMemoryStateStore()
    app = build_flag_on_app(
        test_authority=_IN_PROCESS_TEST_AUTHORITY,
        store=store,
        settings=flag_on_settings(),
    )
    with TestClient(app, raise_server_exceptions=False) as client:
        store._invalid_projection_markers["vibe-trading"] = InvalidProjectionMarker(
            producer_id="vibe-trading",
            offending_sequence=1,
            reason="probe",
            last_known_epoch_sequence=0,
        )
        before = client.portal.call(store.get_execution_events)
        response = client.post(
            "/api/signals",
            json={
                "signal_id": "invalidated-sig",
                "symbol": "AAPL",
                "direction": "buy",
                "thesis": "test",
                "provenance": {"model": "test"},
            },
            headers=headers,
        )
        assert response.status_code == 403
        assert response.json()["reason"] == "producer_quarantined"
        assert client.portal.call(store.get_execution_events) == before


async def test_open_epoch_drift_invalidates_instead_of_raising(tmp_path) -> None:
    """Refutation finding 1 (P0): drift that detonates INSIDE a strict applier
    (ProjectionError, not InvalidEventError) must invalidation per producer at every
    boundary — never escape as an uncaught exception, never wedge release."""

    from datetime import datetime, timezone

    now = datetime(2026, 7, 27, 12, 0, 0, tzinfo=timezone.utc)
    path = str(tmp_path / "opendrift.db")
    store = SqliteStateStore(path)
    await store.initialize()
    for _ in range(2):  # burst 1: opens epoch 1
        await store.check_and_debit_producer_rate(
            "p-drift", now=now, limit_per_hour=60, burst=1
        )

    # Drift the carrier while the epoch is OPEN: the bounded fold's segment
    # contains the opener, so the strict applier's current+1 check detonates.
    assert store._conn is not None
    store._conn.execute(
        "UPDATE signal_producer_rails SET quarantine_epoch_sequence=4 "
        "WHERE producer_id='p-drift'"
    )
    store._conn.commit()

    released = await store.release_producer(
        "p-drift", actor="operator", rejected_count=0, released_at=now
    )
    # The drift funnelled into the heal — no uncaught ProjectionError, no wedge.
    assert released.quarantine_epoch_open is False
    assert store.invalid_projection_markers() == {}  # healed in the same call


# --------------------------------------------------------------------------- #
# Option A (Ameen 2026-07-27): the log-classified release for drift invalidates
# --------------------------------------------------------------------------- #


async def test_open_log_drift_release_is_state1_and_replay_agrees(
    tmp_path,
) -> None:
    """Refutation finding 2, Option A: a drift-invalid-projection producer whose LOG
    folds OPEN gets a NORMAL state-1 release from log truth — replay agrees,
    no re-invalidate, no divergence."""

    from datetime import datetime, timezone

    now = datetime(2026, 7, 27, 12, 0, 0, tzinfo=timezone.utc)
    path = str(tmp_path / "opendrift2.db")
    store = SqliteStateStore(path)
    await store.initialize()
    for _ in range(2):
        await store.check_and_debit_producer_rate(
            "p-a", now=now, limit_per_hour=60, burst=1
        )
    assert store._conn is not None
    store._conn.execute(
        "UPDATE signal_producer_rails SET quarantine_epoch_sequence=4 "
        "WHERE producer_id='p-a'"
    )
    store._conn.commit()

    released = await store.release_producer(
        "p-a", actor="operator", rejected_count=0, released_at=now
    )
    assert store.invalid_projection_markers() == {}
    assert released.quarantine_epoch_sequence == 1  # the LOG's epoch, not row+1

    releases = [
        e
        for e in await store.get_execution_events()
        if e.event_type.value == "producer_released"
    ]
    assert len(releases) == 1
    payload = releases[0].payload
    # A REAL window closed from log truth — NOT a zero-width heal.
    assert payload["epoch_start"] == now.isoformat()

    projection = project_read_models(await store.get_execution_events())
    assert projection.invalid_projection_markers == {}  # replay AGREES — the P0 shape
    fresh = SqliteStateStore(path)
    await fresh.initialize()
    assert fresh.invalid_projection_markers() == {}


async def test_interior_log_drift_is_repaired_and_refused(tmp_path) -> None:
    """Option A: an INTERIOR log means the producer is genuinely mid-cycle —
    releasing it would be the unratified cycle reset F-H forbids. The release
    repairs the cache from log truth, clears the invalidation, and refuses; the
    repair survives the refusal."""

    from app.store.base import ProducerNotQuarantinedError

    path = str(tmp_path / "interior.db")
    store = SqliteStateStore(path)
    await store.initialize()
    r = await store.ingest_signal(
        **_ingest_kwargs("p-b", "bad-1", invalid=True, cycle_budget_limit=3)
    )
    assert r.outcome == "quarantined_validation"

    assert store._conn is not None
    store._conn.execute(
        "UPDATE signal_producer_rails SET cycle_budget_consumed=2 "
        "WHERE producer_id='p-b'"
    )
    store._conn.commit()

    from datetime import datetime, timezone

    now = datetime(2026, 7, 27, 13, 0, 0, tzinfo=timezone.utc)
    with pytest.raises(ProducerNotQuarantinedError):
        await store.release_producer(
            "p-b", actor="operator", rejected_count=0, released_at=now
        )

    # The refusal HEALED: invalidation cleared, row repaired to log truth, no event.
    assert store.invalid_projection_markers() == {}
    rail = await store.get_producer_rail("p-b")
    assert (rail.cycle_budget_limit, rail.cycle_budget_consumed) == (3, 1)
    releases = [
        e
        for e in await store.get_execution_events()
        if e.event_type.value == "producer_released"
    ]
    assert releases == []  # no event for a mid-cycle producer — F-H holds

    ok = await store.ingest_signal(
        **_ingest_kwargs("p-b", "good-after", cycle_budget_limit=3)
    )
    assert ok.outcome == "received"
    projection = project_read_models(await store.get_execution_events())
    assert projection.invalid_projection_markers == {}


# --------------------------------------------------------------------------- #
# Memory-store parity for the invalidated/heal machinery (R-3: both stores are
# first-class — the sqlite pins above have exact memory twins here)
# --------------------------------------------------------------------------- #


async def _memory_with_fixture(fixture: str):
    from app.store.memory import InMemoryStateStore

    store = InMemoryStateStore()
    await store.initialize()
    for event in _events_from_fixture(fixture):
        await store.append_execution_event(event.model_copy(update={"sequence": 0}))
    await store.initialize()  # the tolerant rebuild derives the marker
    return store


async def test_memory_legacy_tolerance_heal_and_resume() -> None:
    """Memory twin of the sqlite legacy pins: invalidated at rebuild, healed by
    the zero-width release, resumed, replay-clean."""

    from datetime import datetime, timedelta, timezone

    store = await _memory_with_fixture("legacy_overbudget_events")
    assert set(store.invalid_projection_markers()) == {LEGACY_PRODUCER}

    gated = await store.ingest_signal(
        **_ingest_kwargs(LEGACY_PRODUCER, "gated", cycle_budget_limit=50)
    )
    assert gated.outcome == "producer_quarantined"
    assert gated.record is None

    released_at = datetime(2026, 7, 27, 13, 0, 0, tzinfo=timezone.utc)
    healed = await store.release_producer(
        LEGACY_PRODUCER, actor="operator", rejected_count=0, released_at=released_at
    )
    assert store.invalid_projection_markers() == {}
    assert healed.quarantine_epoch_sequence == 1

    resumed = await store.ingest_signal(
        **_ingest_kwargs(
            LEGACY_PRODUCER,
            "post-heal",
            cycle_budget_limit=50,
            issued_at=released_at,
            received_at=released_at + timedelta(seconds=1),
        )
    )
    assert resumed.outcome == "received"
    projection = project_read_models(await store.get_execution_events())
    assert projection.invalid_projection_markers == {}


async def test_memory_wedge_gate_and_heal() -> None:
    """Memory twin of the wedge pin: exactly-at-limit legacy state folds as a
    wedge, gates ingest, and releases via the zero-width heal."""

    from datetime import datetime, timezone

    store = await _memory_with_fixture("legacy_wedge_events")
    assert store.invalid_projection_markers() == {}
    rail = await store.get_producer_rail(LEGACY_PRODUCER)
    assert (rail.cycle_budget_limit, rail.cycle_budget_consumed) == (2, 2)

    gated = await store.ingest_signal(
        **_ingest_kwargs(LEGACY_PRODUCER, "gated", cycle_budget_limit=2)
    )
    assert gated.outcome == "producer_quarantined"

    now = datetime(2026, 7, 27, 13, 0, 0, tzinfo=timezone.utc)
    healed = await store.release_producer(
        LEGACY_PRODUCER, actor="operator", rejected_count=0, released_at=now
    )
    assert healed.quarantine_epoch_sequence == 1
    assert store.invalid_projection_markers() == {}


async def test_memory_state1_release_and_open_epoch_restart_still_work(
    monkeypatch,
) -> None:
    """Memory twin of the SQLite F-A healthy-release pin (REV-0045 P0-2): a
    normal, undrifted open-epoch release must clear the bounded check on the
    first try — never transiting the invalidate-then-heal fallback, which would
    silently re-derive the identical correct numbers from a full unseeded
    refold and mask a broken seed formula."""

    from datetime import datetime, timezone

    from app.events.projectors import ProjectionError
    from app.store.base import InvalidEventError
    from app.store.memory import InMemoryStateStore

    now = datetime(2026, 7, 27, 12, 0, 0, tzinfo=timezone.utc)
    store = InMemoryStateStore()
    await store.initialize()
    for _ in range(2):  # burst 1: second call breaches, opens epoch 1
        await store.check_and_debit_producer_rate(
            "producer-open", now=now, limit_per_hour=60, burst=1
        )
    rail = await store.get_producer_rail("producer-open")
    assert rail.quarantine_epoch_open is True
    assert store.invalid_projection_markers() == {}  # a healthy open epoch

    bounded_check_raised: list[BaseException] = []
    original_bounded_check = InMemoryStateStore._authoritative_epoch_sequence_unlocked

    def _spy(self, producer_id, cached):
        try:
            return original_bounded_check(self, producer_id, cached)
        except (InvalidEventError, ProjectionError) as exc:
            bounded_check_raised.append(exc)
            raise

    monkeypatch.setattr(
        InMemoryStateStore, "_authoritative_epoch_sequence_unlocked", _spy
    )

    released = await store.release_producer(
        "producer-open", actor="operator", rejected_count=3, released_at=now
    )
    assert bounded_check_raised == []
    assert released.quarantine_epoch_open is False
    assert released.quarantine_epoch_sequence == 1  # preserved, not consumed
    assert "producer-open" not in store.invalid_projection_markers()


async def test_memory_open_log_drift_release_is_state1() -> None:
    """Memory twin of the Option-A open-log pin."""

    from datetime import datetime, timezone

    from app.store.memory import InMemoryStateStore

    now = datetime(2026, 7, 27, 12, 0, 0, tzinfo=timezone.utc)
    store = InMemoryStateStore()
    await store.initialize()
    for _ in range(2):
        await store.check_and_debit_producer_rate(
            "p-a", now=now, limit_per_hour=60, burst=1
        )
    store._producer_epoch_sequences["p-a"] = 4  # the drift

    released = await store.release_producer(
        "p-a", actor="operator", rejected_count=0, released_at=now
    )
    assert store.invalid_projection_markers() == {}
    assert released.quarantine_epoch_sequence == 1  # the LOG's epoch

    releases = [
        e
        for e in await store.get_execution_events()
        if e.event_type.value == "producer_released"
    ]
    assert releases[0].payload["epoch_start"] == now.isoformat()
    projection = project_read_models(await store.get_execution_events())
    assert projection.invalid_projection_markers == {}


async def test_memory_interior_log_drift_is_repaired_and_refused() -> None:
    """Memory twin of the Option-A interior pin — repair survives the raise
    (the dict updates commit outside the atomic rollback)."""

    from datetime import datetime, timezone

    from app.store.base import ProducerNotQuarantinedError
    from app.store.memory import InMemoryStateStore

    store = InMemoryStateStore()
    await store.initialize()
    r = await store.ingest_signal(
        **_ingest_kwargs("p-b", "bad-1", invalid=True, cycle_budget_limit=3)
    )
    assert r.outcome == "quarantined_validation"
    budget = store._producer_budget_rails["p-b"]
    store._producer_budget_rails["p-b"] = type(budget)(
        cycle_budget_limit=budget.cycle_budget_limit,
        cycle_budget_consumed=2,  # the drift
        quarantine_epoch_open=budget.quarantine_epoch_open,
        quarantine_epoch_started_at=budget.quarantine_epoch_started_at,
        quarantine_breach_trigger=budget.quarantine_breach_trigger,
    )

    now = datetime(2026, 7, 27, 13, 0, 0, tzinfo=timezone.utc)
    with pytest.raises(ProducerNotQuarantinedError):
        await store.release_producer(
            "p-b", actor="operator", rejected_count=0, released_at=now
        )

    assert store.invalid_projection_markers() == {}
    rail = await store.get_producer_rail("p-b")
    assert (rail.cycle_budget_limit, rail.cycle_budget_consumed) == (3, 1)
    ok = await store.ingest_signal(
        **_ingest_kwargs("p-b", "good-after", cycle_budget_limit=3)
    )
    assert ok.outcome == "received"


async def test_release_key_parser_refuses_non_mintable_variants() -> None:
    """Refutation finding 7 pins, as tests rather than a probe transcript.

    REV-0045 P0-3/P1-1: the parser also binds the key to the expected
    producer and rejects a sequence outside the SQLite-representable signed
    range, so a carrier minted for one producer (or one that would overflow
    SQLite but not a Python int) can never be accepted for another.
    """

    from app.events.projectors import (
        _SQLITE_MAX_SIGNED_INT,
        ProjectionError,
        sequence_from_release_dedupe_key,
    )

    assert (
        sequence_from_release_dedupe_key("producer_release:1:p|1:7", producer_id="p")
        == 7
    )
    overflow_value = str(_SQLITE_MAX_SIGNED_INT + 1)
    for bad in (
        "producer_release:1:3",  # single part
        "producer_release:1:p|2:07",  # non-canonical digits
        "producer_release:1:p|1:7|1:9",  # three parts
        "producer_quarantine:1:p|1:7",  # wrong prefix
        "producer_release:1:p|1:0",  # non-positive
        f"producer_release:1:p|{len(overflow_value)}:{overflow_value}",  # overflow
        "producer_release:3:pq|1:7",  # malformed producer length prefix
    ):
        with pytest.raises(ProjectionError):
            sequence_from_release_dedupe_key(bad, producer_id="p")

    # Bound to a DIFFERENT producer: well-formed key, wrong owner.
    with pytest.raises(ProjectionError):
        sequence_from_release_dedupe_key("producer_release:1:p|1:7", producer_id="q")


async def test_memory_anchor_check_uses_dedupe_index_not_a_log_scan() -> None:
    """REV-0045 P1-2: the O(1) anchor lookup must consult the dedupe index
    (mirroring SQLite's keyed query), never scan the raw event list.

    Proven by decoupling the two structures — something only a test can do:
    the anchor key lives ONLY in ``_execution_event_dedupe``, and the raw
    event list stays empty. A scan-based check would find no anchor and
    raise; the dict-based check finds it and succeeds.
    """

    from app.store.base import ProducerRailState
    from app.store.core import signal_dedupe_key
    from app.store.memory import InMemoryStateStore

    store = InMemoryStateStore()
    await store.initialize()

    producer_id = "p-anchor"
    anchor_key = signal_dedupe_key("producer_release", producer_id, "3")
    store._execution_event_dedupe[anchor_key] = object()
    assert store._execution_events == []  # the scan target is deliberately bare

    cached = ProducerRailState(producer_id=producer_id, quarantine_epoch_sequence=3)
    result = store._authoritative_epoch_sequence_unlocked(producer_id, cached)
    assert result == 3


# --------------------------------------------------------------------------- #
# REV-0045 addendum-02 — round-2 findings (P0-5, P0-4, P0-3, P0-2)
# --------------------------------------------------------------------------- #


# Producer ids the ratified config admits (non-blank, valid UTF-8). The mint is
# length-prefixed precisely so EVERY one of these round-trips; '|' is the key
# separator and ':' the length separator, so both must survive, as must a value
# shaped like an entire encoded part.
_ADVERSARIAL_PRODUCER_IDS = (
    "plain-producer",
    "team|alpha",
    "a|b|c",
    "ns:scoped",
    "3:weird",
    "10:team|alpha",
    "münchen-Ω",
    "|",
    ":",
    "|:|",
    "0:",
)


async def test_release_key_parser_is_a_total_inverse_of_the_ratified_mint() -> None:
    """REV-0045 addendum-02 P0-5: the parser must be a TOTAL INVERSE of the
    ratified mint over every producer id configuration admits.

    ``signal_dedupe_key`` length-prefixes each part exactly so that arbitrary
    strings round-trip ("Length-prefixed parts preserve tuple boundaries for
    every string and therefore keep live/replay truth aligned"). A decoder
    that splits the body on the separator instead of consuming each declared
    character count breaks that contract for any producer id containing the
    separator — the store mints a key it can never read back.
    """

    from app.events.projectors import (
        _SQLITE_MAX_SIGNED_INT,
        sequence_from_release_dedupe_key,
    )
    from app.store.core import signal_dedupe_key

    for producer_id in _ADVERSARIAL_PRODUCER_IDS:
        for sequence in (1, 2, 42, _SQLITE_MAX_SIGNED_INT):
            key = signal_dedupe_key("producer_release", producer_id, str(sequence))
            assert (
                sequence_from_release_dedupe_key(key, producer_id=producer_id)
                == sequence
            ), f"mint/parse round-trip failed for {producer_id!r} at {sequence}"


async def test_release_key_parser_stays_injective_across_producers() -> None:
    """The inverse must also stay OWNER-BOUND over adversarial ids: a key
    minted for one producer must never parse as another, including the
    ambiguous pairs the length prefix exists to separate."""

    from app.events.projectors import (
        ProjectionError,
        sequence_from_release_dedupe_key,
    )
    from app.store.core import signal_dedupe_key

    for minted_for in _ADVERSARIAL_PRODUCER_IDS:
        key = signal_dedupe_key("producer_release", minted_for, "7")
        for claimed_by in _ADVERSARIAL_PRODUCER_IDS:
            if claimed_by == minted_for:
                continue
            with pytest.raises(ProjectionError):
                sequence_from_release_dedupe_key(key, producer_id=claimed_by)


async def test_release_key_parser_refuses_a_null_key_on_both_stores() -> None:
    """REV-0045 addendum-02 P0-3 (NULL-key limb): ``dedupe_key`` is nullable on
    the model and the column, and no append path validates it per event type.
    The parser itself must refuse ``None`` as a ProjectionError so BOTH floors
    ignore it identically — SQLite previously passed the raw column value and
    raised an uncaught AttributeError where memory normalized to ''."""

    from app.events.projectors import (
        ProjectionError,
        sequence_from_release_dedupe_key,
    )

    with pytest.raises(ProjectionError):
        sequence_from_release_dedupe_key(None, producer_id="p")


async def test_delimiter_bearing_producer_agrees_live_replay_and_restart(
    tmp_path,
) -> None:
    """REV-0045 addendum-02 P0-5 end-to-end: a producer id containing the key
    separator must open, release, replay, and restart in agreement on BOTH
    stores. Before the decoder fix each store released live and then marked
    that same producer on replay and on every restart — a store-minted
    class-A divergence, and unhealable, because each heal minted an equally
    unreadable key."""

    from datetime import datetime, timezone

    from app.store.memory import InMemoryStateStore

    now = datetime(2026, 7, 28, 12, 0, 0, tzinfo=timezone.utc)
    producer_id = "team|alpha"

    path = str(tmp_path / "pipe.db")
    sqlite_store = SqliteStateStore(path)
    await sqlite_store.initialize()
    memory_store = InMemoryStateStore()
    await memory_store.initialize()

    for store in (sqlite_store, memory_store):
        for _ in range(2):  # burst 1: the second call breaches and opens epoch 1
            await store.check_and_debit_producer_rate(
                producer_id, now=now, limit_per_hour=60, burst=1
            )
        released = await store.release_producer(
            producer_id, actor="operator", rejected_count=0, released_at=now
        )
        assert released.quarantine_epoch_open is False
        assert store.invalid_projection_markers() == {}

        projection = project_read_models(await store.get_execution_events())
        assert projection.invalid_projection_markers == {}, (
            f"replay disagrees with live state for {producer_id!r} "
            f"on {type(store).__name__}"
        )
        assert projection.producer_rails[producer_id].quarantine_epoch_sequence == 1

    restarted = SqliteStateStore(path)
    await restarted.initialize()
    assert restarted.invalid_projection_markers() == {}  # restart agrees too


def _raw_release(
    *, producer_id: str, sequence: int, key_sequence: int, **extra_payload: object
):
    """A PRODUCER_RELEASED event built directly, so a test can attach a payload
    field the ratified builder refuses to mint."""

    from datetime import datetime, timezone

    from app.models import (
        EventAuthority,
        EventSource,
        ExecutionEvent,
        ExecutionEventType,
    )
    from app.store.core import signal_dedupe_key

    when = datetime(2026, 7, 28, 12, 0, 0, tzinfo=timezone.utc)
    return ExecutionEvent(
        sequence=sequence,
        event_type=ExecutionEventType.PRODUCER_RELEASED,
        source=EventSource.ENGINE,
        authority=EventAuthority.LOCAL,
        ts_event=when,
        ts_init=when,
        dedupe_key=signal_dedupe_key(
            "producer_release", producer_id, str(key_sequence)
        ),
        payload={
            "producer_id": producer_id,
            "actor": "operator",
            "rejected_count": 0,
            "epoch_start": when.isoformat(),
            "released_at": when.isoformat(),
            **extra_payload,
        },
    )


def _raw_opener(*, producer_id: str, sequence: int, epoch_sequence: object):
    """A PRODUCER_QUARANTINED event built directly, so a test can place an
    out-of-domain value in the payload carrier the builder would refuse."""

    from datetime import datetime, timezone

    from app.models import (
        EventAuthority,
        EventSource,
        ExecutionEvent,
        ExecutionEventType,
    )
    from app.store.core import signal_dedupe_key

    when = datetime(2026, 7, 28, 12, 0, 0, tzinfo=timezone.utc)
    return ExecutionEvent(
        sequence=sequence,
        event_type=ExecutionEventType.PRODUCER_QUARANTINED,
        source=EventSource.ENGINE,
        authority=EventAuthority.LOCAL,
        ts_event=when,
        ts_init=when,
        dedupe_key=signal_dedupe_key("producer_quarantine", producer_id, str(sequence)),
        payload={
            "producer_id": producer_id,
            "breach_trigger": "rate_breach",
            "bucket_capacity": 5,
            "epoch_start": when.isoformat(),
            "epoch_sequence": epoch_sequence,
        },
    )


async def test_release_high_water_ignores_a_forbidden_payload_sequence() -> None:
    """REV-0045 addendum-02 P0-4: high-water state must not be updated from an
    event before that event's structural source has been validated.

    ``PRODUCER_RELEASED`` has a CLOSED payload that does not ratify
    ``epoch_sequence``; its only structural sequence source is the
    producer-bound dedupe key. Reading the forbidden payload field let an
    unratifiable in-range value raise the marker's high-water, after which the
    live floors (which correctly ignore that field) and replay no longer agree
    on the predecessor sequence — the live store cleared its marker while
    replay and every restart kept it.
    """

    from app.events.projectors import project_producer_rails_tolerant

    producer_id = "p-highwater"
    # Structurally invalid (the extra field breaks the closed payload), so the
    # producer invalidates — and the forbidden field must contribute NOTHING.
    contaminated = _raw_release(
        producer_id=producer_id, sequence=1, key_sequence=1, epoch_sequence=5
    )

    _, invalidated = project_producer_rails_tolerant([contaminated])
    assert producer_id in invalidated
    # This assertion is RE-DERIVED, not edited to match (WO-0141 §3).
    #
    # It previously asserted 1, under the operator's §2.6 RESERVE ruling: a
    # refused release whose key was canonical and producer-bound still reserved
    # its sequence in the high-water mark. That ruling is **WITHDRAWN** (Ameen
    # 2026-07-28, ratifying D-2-b) because it produced P0-6 — a refused event
    # could drive the high-water to the top of the domain, where the human
    # release path has no successor to mint and the rail is unrecoverable.
    #
    # The reservation was answering a real question — the UNIQUE index HAS
    # consumed that key, so a heal at 1 would collide — but answering it in the
    # wrong currency. Occupancy is now tracked as the syntactic fact it is,
    # which is asserted below; proven truth stays 0 because nothing valid was
    # ever proven.
    assert invalidated[producer_id].last_known_epoch_sequence == 0, (
        "a refused event proves nothing (D-2-b) — and the forbidden payload "
        "field (5) must contribute nothing under either ruling"
    )

    # The protective half of this pin, unchanged in substance: the refused
    # event's key is still CONSUMED, so recovery may not land on it. A heal at
    # 1 must be refused and a heal at 2 must be accepted — which is what the
    # withdrawn reservation was reaching for, now expressed where it belongs.
    heal_onto_consumed = _raw_release(
        producer_id=producer_id, sequence=2, key_sequence=1
    )
    _, still_invalid = project_producer_rails_tolerant(
        [contaminated, heal_onto_consumed]
    )
    assert producer_id in still_invalid, "a heal onto a consumed key must refuse"

    heal_at_next = _raw_release(producer_id=producer_id, sequence=2, key_sequence=2)
    healed, cleared = project_producer_rails_tolerant([contaminated, heal_at_next])
    assert producer_id not in cleared, (
        "the heal at the next mintable sequence must clear"
    )
    assert healed[producer_id].quarantine_epoch_sequence == 2


async def test_release_floors_agree_across_stores_on_adversarial_openers(
    tmp_path,
) -> None:
    """REV-0045 addendum-02 P0-3 (floor limb): both stores' release floors must
    judge logged values in ONE type domain.

    SQLite used ``MAX(json_extract(...))`` then an ``isinstance`` check on the
    aggregate, while memory tested each event's Python value. JSON ``true``
    counted as 1 on SQLite and was skipped by memory; a digit string made
    SQLite's cross-type MAX drop every valid opener. Identical logs then minted
    different release keys — the append-only histories themselves diverged.
    """

    from app.store.memory import InMemoryStateStore

    producer_id = "p-floor"
    for adversarial in (True, "9", 3.5, 2**63, None):
        opener = _raw_opener(
            producer_id=producer_id, sequence=1, epoch_sequence=adversarial
        )
        valid = _raw_opener(producer_id=producer_id, sequence=2, epoch_sequence=2)

        memory_store = InMemoryStateStore()
        await memory_store.initialize()
        memory_store._execution_events.extend([opener, valid])
        memory_floor = memory_store._release_sequence_floor_unlocked(producer_id)

        path = str(tmp_path / f"floor-{adversarial!r}.db".replace("/", "_"))
        sqlite_store = SqliteStateStore(path)
        await sqlite_store.initialize()
        assert sqlite_store._conn is not None
        with sqlite_store._tx() as insert_cur:
            for event in (opener, valid):
                sqlite_store._insert_execution_event(
                    insert_cur, event.model_copy(update={"sequence": 0})
                )
        cur = sqlite_store._conn.cursor()
        sqlite_floor = sqlite_store._release_sequence_floor_locked(cur, producer_id)

        assert memory_floor == sqlite_floor == 2, (
            f"floors disagree for opener epoch_sequence={adversarial!r}: "
            f"memory={memory_floor} sqlite={sqlite_floor} (both must ignore the "
            "out-of-domain value and honour the valid opener at 2)"
        )


async def test_durable_rail_sink_refuses_an_out_of_domain_carrier(tmp_path) -> None:
    """REV-0045 addendum-02 P0-3 (sink limb): the ONE non-literal SQLite
    carrier sink must refuse an out-of-domain epoch sequence with a typed
    store error, not let sqlite3 raise ``OverflowError`` mid-``initialize()``
    and leave the database permanently unopenable.

    Every current ingress is now bounded by ``contributed_epoch_sequence``
    and the strict appliers, so this is reached by direct call — that is the
    point. The guard is structural: it holds for a future ingress that
    forgets to bound, which is exactly how this defect class recurred.
    """

    from app.events.projectors import ProducerRailProjection
    from app.store.base import InvalidEventError

    store = SqliteStateStore(str(tmp_path / "sink.db"))
    await store.initialize()
    assert store._conn is not None

    over_domain = ProducerRailProjection(
        producer_id="p-sink",
        quarantine_epoch_sequence=2**63,
    )
    with store._tx() as cur:
        with pytest.raises(InvalidEventError):
            store._upsert_producer_log_rail(cur, over_domain)

    # And the database is still openable afterwards — the refusal is clean.
    reopened = SqliteStateStore(store._db_path)
    await reopened.initialize()
    assert reopened.invalid_projection_markers() == {}


@pytest.mark.parametrize("store_kind", ["sqlite", "memory"])
async def test_bounded_check_never_falls_back_across_consecutive_epochs(
    tmp_path, monkeypatch, store_kind
) -> None:
    """REV-0045 addendum-02 P0-2: the first-try/no-fallback property must hold
    across CONSECUTIVE epochs, not only the first one.

    The round-1 replacement pins released a healthy epoch whose sequence was
    always 1. They distinguish deleting the subtraction, but not a
    subtraction wrongly conditioned on the sequence being exactly 1 — that
    mutant left both pins and the whole 161-test rails corpus green, then at
    epoch 2 raised on a healthy segment and silently entered the
    invalidation/classification fallback, which re-derives the correct rail so no
    result assertion ever fires.

    Driving three consecutive open/release cycles and asserting the bounded
    verifier succeeds on the FIRST try at every one of them is what makes the
    epoch-2+ path observable.
    """

    from datetime import datetime, timezone

    from app.events.projectors import ProjectionError
    from app.store.base import InvalidEventError
    from app.store.memory import InMemoryStateStore

    now = datetime(2026, 7, 28, 12, 0, 0, tzinfo=timezone.utc)
    producer_id = "p-epochs"
    raised: list[BaseException] = []

    if store_kind == "sqlite":
        store = SqliteStateStore(str(tmp_path / "epochs.db"))
        cls, attr = SqliteStateStore, "_authoritative_epoch_sequence_locked"
    else:
        store = InMemoryStateStore()
        cls, attr = InMemoryStateStore, "_authoritative_epoch_sequence_unlocked"
    await store.initialize()

    original = getattr(cls, attr)

    def _spy(self, *args):
        try:
            return original(self, *args)
        except (InvalidEventError, ProjectionError) as exc:
            raised.append(exc)
            raise

    monkeypatch.setattr(cls, attr, _spy)

    for epoch in (1, 2, 3):
        for _ in range(2):  # burst 1: the second call breaches
            await store.check_and_debit_producer_rate(
                producer_id, now=now, limit_per_hour=60, burst=1
            )
        rail = await store.get_producer_rail(producer_id)
        assert rail.quarantine_epoch_open is True
        assert rail.quarantine_epoch_sequence == epoch

        released = await store.release_producer(
            producer_id, actor="operator", rejected_count=0, released_at=now
        )
        assert released.quarantine_epoch_open is False
        assert released.quarantine_epoch_sequence == epoch
        assert store.invalid_projection_markers() == {}
        assert raised == [], (
            f"the bounded verifier fell back at epoch {epoch} on a HEALTHY "
            f"segment ({store_kind}): {raised!r}"
        )

    projection = project_read_models(await store.get_execution_events())
    assert projection.invalid_projection_markers == {}
    assert projection.producer_rails[producer_id].quarantine_epoch_sequence == 3
